### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by aycelacap** [nikumar1206/StreetSmart#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

**Comment by aycelacap** [comment]
Hi Nik, go ahead and add bullet points per document as well as a placeholder for your site! You can use the real site for now!

**Comment by nikumar1206** [comment]
Hey Ayce! I think these issues should be resolved now!

**Comment by aycelacap** [comment]
Looks great so far! Thank you!
